---
# tasks file for lvextend

- block:
    - name: Check if logical volume needs extending
      shell: "lvdisplay --units g /dev/rootvg/rootlv | grep 'LV Size' | awk '{ print $3 }'"
      register: lv_size
      failed_when: lv_size.rc != 0

    - name: Debug lv_size
      debug:
         var: lv_size

    - block:
        - name: Extend logical volume if free space is less than {{ lv_extension_threshold }}G
          debug:
            msg: "Extending logical volume by {{ lv_extension_threshold }}G"
          when: lv_size.stdout_lines[0] | int < lv_extension_threshold

        - name: Extend logical volume if free space is less than threshold {{ lv_extension_threshold }}
          lvol:
            vg: rootvg
            lv: rootlv
            size: "{{ lv_extension_threshold }}G"
          register: lv_extend
          when: lv_size.stdout_lines[0] | int < lv_extension_threshold


        - name: Extend logical volume to maximum if free space
          debug:
            msg: "Extending logical volume to maximum"
          when: lv_extend.changed

        - name: Extend logical volume to maximum if free space
          lvol:
            vg: rootvg
            lv: rootlv
            size: +100%FREE
          when: lv_extend.changed

  become: yes
