---
# tasks file for pre-setup
- name: Ping hosts
  ping:

- name: Create oinstall group if it doesn't exist
  group:
    name: oinstall
    gid: 501
    state: present
  become: yes  

- name: Create dba group if it doesn't exist
  group:
    name: dba
    gid: 502
    state: present
  become: yes  

- name: Create oracle user
  user:
    name: oracle
    uid: 501
    group: oinstall
    groups: dba
    state: present  
  become: yes  


- name: Create the Oracle Inventory Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - chown -R oracle:oinstall /u01
  register: u_perm
  become: yes


- name: Create the Oracle Inventory Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/oraInventory
    - chown -R oracle:oinstall /u01/app/oraInventory
    - chmod -R 775 /u01/app/oraInventory
  register: user_perm  
  become: yes
  become_user: oracle


- name: Creating the Oracle Grid Infrastructure Base and  Home Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/19.3.0/db
    - mkdir -p /u01/app/19.3.0/grid
    - chown -R oracle:oinstall /u01/app/19.3.0/db
    - chown -R oracle:oinstall /u01/app/
    - chmod -R 775 /u01/app/19.3.0/grid 
  register: oracle_info
  become: yes
  become_user: oracle

- name: Creating Oracle Software directory
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/oracle/software
    - chown -R oracle:oinstall /u01/app/oracle/software
  register: oracle_soft
  become: yes
  become_user: oracle   

- name: Set SELINUX to disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  register: sel_data  
  become: yes    

- name: Reboot the machine
  block:
    - name: Reboot the system
      shell: sleep 5 && init 6
      async: 1 
      poll: 0 

    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 60
        timeout: 300
  become: yes
  when: sel_data.changed == true

