---
- name: Playbook to execute ping role
  hosts: rhel-db-servers
  vars_files:
    - vars.yml  
  roles:
      - lvextend
      - partitions-mount
      - swapspace
      - user-directory-setup
      - reboot
      - grid-install  
