---
- name: Playbook to execute ping role
  hosts: rhel-db-servers
  vars_files:
    - vars.yml  
  roles:
    - lvextend-operations  
    - grow-partition-operations
    - osdisk-operations     
    - extra-disk-operations
    - user-directory-setup
    - reboot
    - grid-requirements 
    - grid-install 
    - database-install
    - database-creation
