---
- name: Playbook to execute ping role
  hosts: rhel-db-servers
  vars_files:
    - vars.yml  
  roles:
          #- lvextend   
          #- volume_operations
          #- partitioning_mounting_osdisk     
          #- partitions-mount
          #- user-directory-setup
          #- reboot
    - pre-req-grid  
    - grid-install  
