---
# tasks file for pre-setup
- name: Ping hosts
  ping:

- name: Partition disks if root user
  parted:
    device: "{{ item }}"
    label: gpt
    part_type: primary
    file_system: xfs
    name: primary
    start: 0%
    end: 100%
  loop:
    - /dev/sde
    - /dev/sdf
  become: yes

- name: Create ASM disks if root user
  command: "oracleasm createdisk {{ item.disk_group }} {{ item.disk }}"
  loop:
    - { disk_group: "DATA", disk: "/dev/sde1" }
    - { disk_group: "RECO", disk: "/dev/sdf1" }
  become: yes

- name: Source grid environment
  become_user: oracle
  shell: "source grid_env"
  become: yes

- name: Create ASM Disk Groups
  become_user: oracle
  shell: "asmca -silent -createDiskGroup -diskString '/dev/oracleasm/disks/*' -diskGroupName {{ item.disk_group }} -diskList '/dev/oracleasm/disks/{{ item.disk_group }}*' -redundancy EXTERNAL"
  loop:
    - { disk_group: "DATA" }
    - { disk_group: "RECO" }
  become: yes    

- name: List ASM Disk Groups
  become_user: oracle
  shell: "asmcmd lsdg"
  register: asm_disk_groups
  become: yes

- name: Source Oracle user profile
  become_user: oracle
  shell: "source .bash_profile"
  become: yes

- name: Check if ASM Disk Groups are created
  debug:
    msg: "ASM Disk Group {{ item.disk_group }} already exists."
  loop:
    - { disk_group: "DATA" }
    - { disk_group: "RECO" }
  when: "'+' + item.disk_group in asm_disk_groups.stdout"

- name: Run dbca command to create Oracle database
  become_user: oracle
  shell: |
    dbca -silent -createDatabase \
    -gdbName TESTCDB2 \
    -sid TESTCDB2 \
    -responseFile NO_VALUE \
    -databaseConfigType SI \
    -dbOptions JSERVER:true,ORACLE_TEXT:false,IMEDIA:false,CWMLITE:false,SPATIAL:false,OMS:false,APEX:false,DV:false \
    -createAsContainerDatabase true \
    -numberOfPDBs 1 \
    -pdbName TESTPDB02 \
    -pdbAdminPassword E4CQmk3ps65N8xBc \
    -databaseType MULTIPURPOSE \
    -templateName New_Database.dbt \
    -sysPassword gyoFm8AYHsvZm48A \
    -systemPassword gyoFm8AYHsvZm48A \
    -storageType ASM \
    -diskGroupName +DATA \
    -recoveryGroupName +RECO \
    -redoLogFileSize 50 \
    -useOMF true \
    -totalMemory 4096 \
    -characterSet AL32UTF8 \
    -sampleSchema false \
    -initParams "sga_target=1536MB,pga_aggregate_target=512MB,nls_language=ENGLISH,nls_territory='AMERICA',db_create_online_log_dest_1='+DATA',processes=300,open_cursors=300,db_recovery_file_dest_size=1GB" \
    -automaticMemoryManagement false
  become: yes

- name: Run ps command to check for pmon processes
  shell: "ps -ef | grep pmon"
  register: pmon_processes
  changed_when: false

- debug:
     msg: "pmon processes: {{ pmon_processes.stdout }}"

- name: Create Oracle Database
  become_user: oracle
  shell: "/u01/app/19.3.0/grid/bin/crsctl stop has"
  become: yes          
