---
# tasks file for grid-install


# tasks file for pre-setup
- name: Ping hosts
  ping:

- block:
    - name: Check if Oracle user's home directory exists
      stat:
        path: "/home/oracle"
      register: oracle_home_stat

    - name: Create Oracle user's home directory if it doesn't exist
      file:
        path: "/home/oracle"
        state: directory
      when: not oracle_home_stat.stat.exists

    - name: Copy .bash_profile template to Oracle user's home directory
      template:
        src: "bash_profile.j2"
        dest: "/home/oracle/.bash_profile"
        owner: oracle
        group: oinstall
        mode: "0644"
  become: yes
  become_user: oracle          

- name: Copy file using rsync
  synchronize:
    src: /home/eppadmin/oracle-packages/
    dest: /u01/app/oracle/software
  become: yes

- name: Ensure software directory exists
  stat:
    path: /u01/app/oracle/software
  register: software_dir
  become: yes

- name: Check if oracle-database-preinstall-19c is installed
  command: rpm -q i oracle-database-preinstall
  register: oracle_database_preinstall_installed
  changed_when: false
  failed_when: false
  become: yes
  

- name: Install oracle-database-preinstall-19c
  yum:
    name: /u01/app/oracle/software/oracle-database-preinstall-19c-1.0-2.el8.x86_64.rpm
    state: present
  when: oracle_database_preinstall_installed.rc != 0
  become: yes  

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - bc
    - binutils
    #- compat-libcap1
    #- compat-libstdc++-33
    #- dtrace-utils
    - elfutils-libelf
    - elfutils-libelf-devel
    - fontconfig-devel
    - glibc
    - glibc-devel
    - ksh
    - libaio
    - libaio-devel
    #- libdtrace-ctf-devel
    - libXrender
    - libXrender-devel
    - libX11
    - libXau
    - libXi
    - libXtst
    - libgcc
    - librdmacm-devel
    - libstdc++
    - libstdc++-devel
    - libxcb
    - make
    - smartmontools
    - sysstat
    - libnsl
    - libnsl.i686
    - libnsl2
    - libnsl2.i686  
  become: yes

- name: Update all packages
  yum:
    name: "*"
    state: latest
  become: yes
