---
# tasks file for pre-setup-obs
- name: Ping hosts
  ping:

- name: Create oinstall group if it doesn't exist
  group:
    name: oinstall
    gid: 501
    state: present
  become: yes  

- name: Create dba group if it doesn't exist
  group:
    name: dba
    gid: 502
    state: present
  become: yes  

- name: Create oracle user
  user:
    name: oracle
    uid: 501
    group: oinstall
    groups: dba
    state: present  
  become: yes  


- name: Create the Oracle Inventory Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - chown -R oracle:oinstall /u01
  register: u_perm
  become: yes


- name: Create the Oracle Inventory Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/oraInventory
    - chown -R oracle:oinstall /u01/app/oraInventory
    - chmod -R 775 /u01/app/oraInventory
  register: user_perm  
  become: yes
  become_user: oracle


- name: Creating the Oracle Grid Infrastructure Base and  Home Directory as 'oracle' user
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/19.3.0/db
    - chown -R oracle:oinstall /u01/app/19.3.0/db
    - chown -R oracle:oinstall /u01/app/
  register: oracle_info
  become: yes
  become_user: oracle

- name: Creating Oracle Software directory
  shell: "{{ item }}"
  with_items:
    - mkdir -p /u01/app/oracle/software
    - chown -R oracle:oinstall /u01/app/oracle/software
  register: oracle_soft
  become: yes
  become_user: oracle   

- name: Set SELINUX to disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  register: sel_data  
  become: yes    

- name: Reboot the machine
  block:
    - name: Reboot the system
      shell: sleep 5 && init 6
      async: 1 
      poll: 0 

    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 60
        timeout: 300
  become: yes
  when: sel_data.changed == true

- block:
    - name: Check if Oracle user's home directory exists
      stat:
        path: "/home/oracle"
      register: oracle_home_stat

    - name: Create Oracle user's home directory if it doesn't exist
      file:
        path: "/home/oracle"
        state: directory
      when: not oracle_home_stat.stat.exists

    - name: Copy .bash_profile template to Oracle user's home directory
      template:
        src: "bash_profile.j2"
        dest: "/home/oracle/.bash_profile"
        owner: oracle
        group: oinstall
        mode: "0644"
  become: yes
  become_user: oracle          

- name: Copy file using rsync
  synchronize:
    src: /home/eppadmin/oracle-packages/
    dest: /u01/app/oracle/software
  become: yes

- name: Ensure software directory exists
  stat:
    path: /u01/app/oracle/software
  register: software_dir
  become: yes

- name: Check if oracle-database-preinstall-19c is installed
  command: rpm -q i oracle-database-preinstall
  register: oracle_database_preinstall_installed
  changed_when: false
  failed_when: false
  become: yes
  

- name: Install oracle-database-preinstall-19c
  yum:
    name: /u01/app/oracle/software/oracle-database-preinstall-19c-1.0-2.el8.x86_64.rpm
    state: present
  when: oracle_database_preinstall_installed.rc != 0
  become: yes  

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - bc
    - binutils
    #- compat-libcap1
    #- compat-libstdc++-33
    #- dtrace-utils
    - elfutils-libelf
    - elfutils-libelf-devel
    - fontconfig-devel
    - glibc
    - glibc-devel
    - ksh
    - libaio
    - libaio-devel
    #- libdtrace-ctf-devel
    - libXrender
    - libXrender-devel
    - libX11
    - libXau
    - libXi
    - libXtst
    - libgcc
    - librdmacm-devel
    - libstdc++
    - libstdc++-devel
    - libxcb
    - make
    - smartmontools
    - sysstat
    - libnsl
    - libnsl.i686
    - libnsl2
    - libnsl2.i686  
  become: yes

- name: Update all packages
  yum:
    name: "*"
    state: latest
  become: yes  