---
# tasks file for pre-setup
- name: Ping hosts
  ping:

- name: Apply OPatch in Oracle Home
  become: yes
  become_user: oracle
  shell: |
    cd /u01/app/19.3.0/db
    /u01/app/19.3.0/db/OPatch/opatch version

- name: Move OPatch directory in Oracle Home
  become: yes
  become_user: oracle
  shell: mv OPatch OPatch-12.2.0.1.17
  args:
    chdir: /u01/app/19.3.0/db

- name: Unzip OPatch in Oracle Home
  become: yes
  become_user: oracle
  shell: unzip -q /u01/app/oracle/software/p6880880_190000_Linux-x86-64.zip -d /u01/app/19.3.0/db/

- name: Set permissions in Oracle Home for OPatch
  become: yes
  become_user: oracle
  shell: |
    chmod 755 -R OPatch
    chown oracle:oinstall -R OPatch
  args:
    chdir: /u01/app/19.3.0/db

- name: Check OPatch version in Oracle Home after setup
  become: yes
  become_user: oracle
  shell: /u01/app/19.3.0/db/OPatch/opatch version

- name: Apply OPatch in Grid Home
  become: yes
  shell: |
    cd /u01/app/19.3.0/grid/
    /u01/app/19.3.0/grid/OPatch/opatch version

- name: Move OPatch directory in Grid Home
  become: yes
  shell: mv OPatch OPatch-12.2.0.1.17
  args:
    chdir: /u01/app/19.3.0/grid

- name: Unzip OPatch in Grid Home
  become: yes
  shell: unzip -q /u01/app/oracle/software/p6880880_190000_Linux-x86-64.zip -d /u01/app/19.3.0/grid/

- name: Set permissions in Grid Home for OPatch
  become: yes
  shell: |
    chmod 755 -R OPatch
    chown oracle:oinstall -R OPatch
  args:
    chdir: /u01/app/19.3.0/grid

- name: Check OPatch version in Grid Home after setup
  become: yes
  shell: /u01/app/19.3.0/grid/OPatch/opatch version

- name: Create patch directory
  become: yes
  become_user: oracle
  shell: mkdir -p /u01/app/oracle/software/patches/19.15.0

- name: Copy patch file to Oracle Home
  become: yes
  become_user: oracle
  shell: unzip -q p33859214_190000_Linux-x86-64.zip -d /u01/app/oracle/software/patches/19.15.0

- name: Apply patch in Grid Home
  become: yes
  shell: /u01/app/19.3.0/grid/OPatch/opatchauto apply /u01/app/oracle/software/patches/19.15.0/33859214/33803476          
