---
# tasks file for lvextend
- name: Check if marker for successful lvextend exists in file
  shell: "grep -i 'successful lvextend execution' /tmp/oracle_status.txt"
  register: lvextend_status
  ignore_errors: yes

- block:
    - name: Check if logical volume needs extending
      shell: "lvdisplay --units g /dev/rootvg/{{ item.lvpath }} | grep 'LV Size' | awk '{ print $3 }'"
      register: lv_size
      failed_when: lv_size.rc != 0
      loop: "{{ lv_extension_threshold }}"

    - name: Debug lv_size
      debug:
         var: lv_size

    - block:
        - name: Extend logical volume if free space is less than {{ item.resize }}G
          debug:
            msg: "Extending logical volume by {{ item.resize }}G"
          loop: "{{ lv_extension_threshold }}"
          loop_control:
            index_var: item_index

        - name: Extend logical volume if free space is less than threshold {{ item.resize }} G
          lvol:
            vg: rootvg
            lv: "{{ item.lvpath }}"
            size: "{{ item.resize }}G"
          register: lv_extend
          loop: "{{ lv_extension_threshold }}"
          loop_control:
            index_var: item_index

        - name: Add marker to indicate successful lvextend execution
          lineinfile:
            path: /tmp/oracle_status.txt
            line: "successful lvextend execution"
            create: yes

  become: yes
  when: lvextend_status is changed and lvextend_status.rc != 0

